[project]
name = "slackbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arxiv>=2.2.0",
    "gspread>=6.2.1",
    "oauth2client>=4.1.3",
    "rich>=14.1.0",
    "slack-bolt>=1.25.0",
]
